# Original source from OpenTelecom:ci-linting, mira-t on github
plugins:
  - standard
  - promise
env:
  browser: true
  jquery: true

globals:
  winkstart: true
  form2object: true
  _t: true
  Sentry: true

rules:
  no-tabs: 0
  indent: [ "error", "tab", { "SwitchCase": 1 }]
