# Original source from OpenTelecom:ci-linting, mira-t on github
plugins:
  - standard
env:
  browser: true
  jquery: true

globals:
  winkstart: true
  form2object: true
  _t: true

rules:
  no-tabs: 0
  indent: [ "error", "tab", { "SwitchCase": 1 }]
  linebreak-style: [ "error", "unix" ]
