steps:
  - trigger: 'kazoo-ui-tests'
    branches: '${BUILDKITE_BRANCH}'
    build:
      message: '${BUILDKITE_MESSAGE}'
      commit: '${BUILDKITE_COMMIT}'
      branch: '${BUILDKITE_BRANCH}'

  - wait

  - label: ':construction: Build package'
    command: './scripts/buildkite-build-rpm.sh'
    artifact_paths: '*.rpm'
    agents:
      docker: 'true'
    plugins:
      docker#v1.0.0:
        image: 'voxter/fpm'
        workdir: /app

  - wait

  - label: ':ship: Update YUM repo with new package'
    command: './scripts/buildkite-deploy-rpm.sh'
    agents:
      queue: 'repo'
      repo: 'yum'
